engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - python
        - javascript
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - playlistr/playlistr/**
  - playlistr/spotify_playlists**
exclude_paths:
- playlistr/spotify_playlists/migrations/**/*
- playlistr/spotify_playlists/tests.py