# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_target_duration_time', models.PositiveIntegerField()),
                ('_last_used', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('_spotify_email', models.EmailField(max_length=254)),
                ('_access_token', models.CharField(max_length=200)),
                ('_refresh_token', models.CharField(max_length=200)),
                ('_token_expiry', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPartyJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotify_playlists.Party')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotify_playlists.User')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotify_playlists.User'),
        ),
    ]
