# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_playlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='_creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='_last_used',
            new_name='last_used',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='_target_duration_time',
            new_name='target_duration_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_access_token',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_refresh_token',
            new_name='refresh_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_spotify_email',
            new_name='spotify_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_token_expiry',
            new_name='token_expiry',
        ),
    ]
