# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_playlists', '0003_auto_20160210_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='party_start_date',
            field=models.DateField(default=datetime.datetime(2016, 2, 11, 17, 47, 16, 172768)),
            preserve_default=False,
        ),
    ]
