# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_playlists', '0004_party_party_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
