# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_playlists', '0005_auto_20160213_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='target_duration_time',
            new_name='target_no_songs',
        ),
    ]
