# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_playlists', '0007_remove_party_party_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='name',
            field=models.CharField(default='My Party', max_length=64),
            preserve_default=False,
        ),
    ]
