# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_playlists', '0008_party_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpartyjoin',
            name='party',
        ),
        migrations.RemoveField(
            model_name='userpartyjoin',
            name='user',
        ),
        migrations.AddField(
            model_name='party',
            name='users',
            field=models.ManyToManyField(related_name='users', related_query_name='user', to='spotify_playlists.User'),
        ),
        migrations.DeleteModel(
            name='UserPartyJoin',
        ),
    ]
