# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_playlists', '0009_auto_20160404_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='admins',
            field=models.ManyToManyField(related_name='admins', related_query_name='admin', to='spotify_playlists.User'),
        ),
    ]
